### ISSUE TITLE
Update links on yapc.org

### ISSUE THREAD

**Issue by toddr** [perlconference/tpc-2019-pit#10]
I've not looked at what needs doing here. I have a commit bit though. https://github.com/tpf/yapc-org-website

**Comment by atoomic** [comment]
that repo was not updated over the last 4 years whereas the website has mention of TPC in SLC from last year 2018... 
Not sure this is the correct fork, the dual-life one seems also outdated.. 

@szabgab any chance you can provide feedback where lives the last version of the yapc.org website?

**Comment by szabgab** [comment]
I looked in my email and according to some messages from 2015 this https://github.com/tpf/yapc-org-website was a dump of the site back then. Either @cbrandtbuffalo or @ranguard might know more.

**Comment by ranguard** [comment]
Sorry @szabgab I don't know.. punting on.. @abh any clue where current yapc.org is pulled from - I can see develooper.com is hosting it

**Comment by cbrandtbuffalo** [comment]
The latest version is the one sitting on the live server. It's not pulled from anywhere, we used to build it manually and copy it to the server. The plan is to move it to make it easier to update. I need to find a volunteer to work on it.

**Comment by toddr** [comment]
@cbrandtbuffalo can you update the front page to reflect this year's conferences please? http://www.yapc.org/

**Comment by cbrandtbuffalo** [comment]
I don't have direct access to the server any longer. The plan is to move those pages over to the main perlfoundation.org site under /yapc and redirect yapc.org there. I'll try to move the yapc front page as soon as I can. I'm happy to give out edit rights on the site if anyone else wants to work on it.

**Comment by toddr** [comment]
@cbrandtbuffalo I will take rights if that's the fastest way to get it done

**Comment by abh** [comment]
We can put the yapc site in a separate git repository too if someone / anyone will maintain it.

**Comment by cbrandtbuffalo** [comment]
@toddr Just sent you an invitation
