### ISSUE TITLE
Assign a non-default avatar image to the wiki

### ISSUE THREAD

**Issue by drforr** [perlconference/tpc-2019-pit#11]
Twitter linked to a default avatar image for my recent posting of the Origami BOF, it'd be nice to have the TPCiP 2019 logo appear instead.

**Comment by toddr** [comment]
Sorry, what post do you mean? are we talking about the github wiki and if so how do I change that? or are you talking about the twitter icon?

**Comment by drforr** [comment]
Oh, sorry, bad reporting, it's for Twitter and probably Facebook as well. You just need to change the image for the 'perlconference' user - that's what Twitter is fetching. If you've got access to the image used for the @perlconference user on Twitter that'd be fine. I'm probably the first one to RT something from the wiki anyway, so I'm just the canary in the proverbial coal mine.

Here's the tweet in question.

https://twitter.com/DrForr/status/1103395632314634241

**Comment by toddr** [comment]
This is done but twitter caches abound

**Comment by drforr** [comment]
Of course, but at least in the future we'll have a shiny avatar for tweets, thanks a lot!
