### ISSUE TITLE
Broken links on registration page

### ISSUE THREAD

**Issue by wallisds** [perlconference/tpc-2019-pit#15]
3rd paragraph/line on the registration page under says "The main event" and links to https://perlconference.us/tpc-2019-pit/sessions/ which is a 404. The master class/tutorials link is broken as well, pointing to https://perlconference.us/tpc-2019-pit/tutorials/.

Thanks,

**Comment by toddr** [comment]
I've corrected the sessions link to go to sched.

**Comment by toddr** [comment]
Until I'm told otherwise, I'm going to send the tutorials to https://tpcip.sched.com/tickets
