### ISSUE TITLE
Tuesday night river cruise not on website

### ISSUE THREAD

**Issue by waltman** [perlconference/tpc-2019-pit#19]
It’s listed in the schedule in the Sched app, but it’s not on the schedule that’s on the website.

**Comment by dwright** [comment]
The schedule on the website is embedded directly from sched.    The river cruise is showing up fine to me on the website.

**Comment by waltman** [comment]
This is what Tuesday afternoon looks like to me: https://share.icloud.com/photos/0XizytiRafyjhsXJnDCK1P9Iw

**Comment by dwright** [comment]
Note the instructions at the top of the schedule:   "Drag right to view more."

**Comment by waltman** [comment]
Oh, it's all the way over there! I don't suppose it's possible to add scrollbars so you can actually see that there's a lot more data over to the right?
