### ISSUE TITLE
Online schedule renders poorly on iOS

### ISSUE THREAD

**Issue by waltman** [perlconference/tpc-2019-pit#20]
Here’s a screenshot of what Tuesday morning looks like in Safari on my iPad: https://share.icloud.com/photos/0mRlNuD-JS6hHU32Q5tMHgA_Q

This makes it really difficult to use. I think it would probably all fit if there wasn’t so much white space along the left and right sides.

**Comment by dwright** [comment]
I highly recommend installing the mobile app for iOS.     

https://tpcip.sched.com/mobile-site

**Comment by waltman** [comment]
I've already got it installed. But people coming to the site for information about the con are going to see this version first, and it really leaves a lot to be desired.

**Comment by dwright** [comment]
Well, I agree the grid view embedded on the website isn't very useful in a mobile view.          

I wonder if it's possibly to embed the list view instead?    Or possibly even make it reactive?

**Comment by autarch** [comment]
We can embed the list view, but I think the grid view is just more useful. I don't think there's a way to show one for mobile and one for not.

**Comment by toddr** [comment]
I've adjusted the view and it looks right by default on my iphone. Please let me know if anyone's having issues.
