### ISSUE TITLE
Re-Captia popout is on every page

### ISSUE THREAD

**Issue by toddr** [perlconference/tpc-2019-pit#4]
Contact manager 7 just upgraded to Re-captia v3. When I provided the new google re-captia credentials, we started getting popups on all pages.

This link explains how to fix it but I'd prefer @autarch look at it and advise.

https://wordpress.org/support/topic/annoying-floating-recaptcha-box/

**Comment by toddr** [comment]
> bhoover (@alconebay)
> 1 day, 21 hours ago
> This worked for me. It will hide the badge on all pages that don’t use CF7. This css and javascript should be used site-wide:
> 
> Add this css:
> 
> .grecaptcha-badge {display:none;}
> 
> Add this javascript:
> 
> grecaptcha.ready(function() {
> if ($(‘div.wpcf7’).length) {
> $(‘.grecaptcha-badge’).css( “display”, “block” );
> }
> });

**Comment by autarch** [comment]
Fixed.
