### ISSUE TITLE
Sponsors page

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2019-pit#5]
Need a page to list sponsors / how to sponsor.

Got an email from a potential sponsor today that had difficulty location sponsorship information about the event.    We want to try to make that really easy to find.

**Comment by autarch** [comment]
What should the page content be?

**Comment by autarch** [comment]
This is done.

**Comment by IrishPebbles** [comment]
**Please update the Sponsor page to include the following information:**

Thank you for your interest in sponsoring The Perl Conference! The preferred sponsorship method for TPC is to sponsor The Perl Foundation (TPF). The Perl Foundation is an organization created to cultivate an open-source ecosystem around the Perl programming language. It does this through a series of programs that are funded primarily through sponsorships and donations.

A full donation prospectus (including Donation Level information) can be found here: https://www.perlfoundation.org/donation-prospectus.html

Here’s the quick version:

If you donate at least $6,000, that would make you a Bronze level sponsor.  You would become a sponsor of The Perl Conference, as well as all other TPF events for a full year. Donation levels, and associated benefits, go up from there, through our $100,000 Diamond level sponsorship.

If $6,000 is a bit above your budget, then we do have other sponsorship options available specifically for The Perl Conference.  

As a guideline:

For every $1,000 donated we provide one free, full-access pass to the event for your employees.
Any donation above $500 gets you a table at our “Sponsor Expo” on Tuesday. You would receive a table in a high traffic area for the full day, where you can showcase your products and/or recruit developers.
A donation of at least $500 will also get you two passes to the Sponsor Dinner. This is a limited attendance event where you will have the opportunity to converse with key players from the Perl community. Attendees include members of the Board of Directors of The Perl Foundation, Perl inventor Larry Wall, and lead developers of both Perl 5 and Perl 6. Bronze level donors receive 4 passes and Silver level donors receive 8 passes.

If you would like additional exposure, we have several á la carte items. These include Wi-Fi Sponsor, Social Event Sponsor, Breakfast Sponsor, Name Badge Sponsor, Gift Bag Sponsor, and more. These sponsorship opportunities are all customizable depending on how you would like to promote your brand. Pricing for these items are negotiable depending on your needs.
If you need a custom invoice, I can generate one and send it to you. We can accept payments via bank check, PayPal, credit card, or wire transfer.

If you have any additional questions, please don’t hesitate to email us at admin@perlconference.us.

**Comment by autarch** [comment]
I updated the page. I made some small edits to the text for grammar (notably just using simple future tense instead of conditional "you will" vs "you would").
