### ISSUE TITLE
Anniversary page

### ISSUE THREAD

**Issue by dwright** [perlconference/tpc-2019-pit#7]
It would be nice to develop a page on the website that features the 20th anniversary of the event.    

One thing in particular that would be nice is a listing of the previous 19 events.

**Comment by toddr** [comment]
@dwright do you mean this? https://perlconference.us/tpc-2019-pit/past-perl-conferences/

**Comment by dwright** [comment]
@toddr  Yes, that's the data I was looking for.   Though probably not the presentation style I hoped for.   I guess I need to come up with some copy to apply to that page.    

Also:   How does one actually navigate to that page from the home page?

**Comment by toddr** [comment]
As a mirror of last year, it's at the bottom of every page "Past Perl Conferences"
